version: "3"
services:
  postgres:
    container_name: notification-postgres
    image: postgres:11.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: notification-zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: notification-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "challenge.notification.events:1:1,notifications.autopilot.events:1:1,admin.notification.broadcast:1:1,notifications.action.create:1:1,external.action.email:1:1"

  tc-bus-api:
    container_name: tc-bus-api
    build:
      context: ./generic-tc-service
      args:
        NODE_VERSION: 8.11.3
        GIT_URL: https://github.com/topcoder-platform/tc-bus-api
        GIT_BRANCH: dev
        BYPASS_TOKEN_VALIDATION: 1
    command: start
    ports:
      - 8002:8002
    depends_on:
      - kafka
    environment:
      - PORT=8002
      - KAFKA_URL=kafka:9093
      - JWT_TOKEN_SECRET=secret
      - VALID_ISSUERS="[\"https:\/\/topcoder-newauth.auth0.com\/\",\"https:\/\/api.topcoder-dev.com\",\"https:\/\/topcoder-dev.auth0.com\/\"]"
      - AUTH0_URL
      - AUTH0_AUDIENCE
      - AUTH0_CLIENT_ID
      - AUTH0_CLIENT_SECRET
      - AUTH0_PROXY_SERVER_URL
